### ISSUE TITLE
obfs性能问题

### ISSUE THREAD

**Issue by aglent** [imgk/simple-obfs-Cygwin#13]
原来用的是 https://github.com/shadowsocks/simple-obfs 一切正常
现在改用这个版本，发现下载上传速度很慢。
用的机场服务 办公100Mb宽带 家里500Mb宽带 下载速度只有10Mb不到
试过tls和http混淆 一个样
有谁遇到和我一样的问题吗？

**Comment by imgk** [comment]
这个版本没有修改任何代码，之所以存在是因为曾经一段时间  https://github.com/shadowsocks/simple-obfs 不提供 Windows 版本，所以用 MSYS2 编译，由于 MSYS2 的原因，性能不行是正常现象
