### ISSUE TITLE
Request Cygwin build instructions for simple-obfs

### ISSUE THREAD

**Issue by joynbless** [imgk/simple-obfs-Cygwin#16]
Hey @imgk, would you please open source how to build simple-obfs for Windows using Cygwin?
Could barely search it out anywhere on web? Your help are greatly appreciated.

Thanks.

**Comment by imgk** [comment]
Hi, there is no need to open source the instruction as the procedures are identical to procedures when compiling under linux. I recommend Msys2 comparing with Cygwin.

**Comment by joynbless** [comment]
It turns out building it on pure msys2 MingGW 64 bit, the binary(i.e. executable) fails to run from my side. Instead, the docker build infra from shadowsocks-libev can be reused and minor customized to build simple-obfs Windows executable, and it works as is.

Thank you @imgk though.
