### ISSUE TITLE
v0.0.4在Windows10下运行报错

### ISSUE THREAD

**Issue by YogiLiu** [imgk/simple-obfs-Cygwin#5]
Shadowsocks版本：4.0.6
报错信息如下：
![报错](http://wx1.sinaimg.cn/mw690/005KDf2dgy1fld9882hquj30dg04sjrd.jpg)

**Comment by imgk** [comment]
抱歉，可能我把 mingw 添加到 path 中，所以我在测试时没问题，可以从网上下载这个 DLL，或者先用 msys2 版，等我明天传上去

**Comment by cuoo** [comment]
同样问题。网上搜这个dll大都是些国产下载站，不太敢下载。（笑哭

**Comment by cuoo** [comment]
下载msys2可用。谢谢。

**Comment by freezedcat** [comment]
问下大佬，我把服务器的obfs更新到最新，win客户端libwinpthread-1.dll  msys-2.0.dll  obfs-local.exe也是最新的。其他配置并未更改，用的http混淆，现在显示服务器拒绝连接。这是有啥大的变化吗？

**Comment by imgk** [comment]
@freezedcat 我只是编译一下，没改代码，所以配置问题参考 simple-obfs
