### ISSUE TITLE
MinGW 版运行出错

### ISSUE THREAD

**Issue by AnyoeDove** [imgk/simple-obfs-Cygwin#6]
![image](https://user-images.githubusercontent.com/10519576/32698064-05cf346c-c7d9-11e7-9c53-0c279ced4290.png)
已经下载了 libwinpthread-1.dll，可以正常输出帮助内容，但是单独运行或者搭配 Shadowsocks-windows 就会报错退出。

Windows 10 LTSB 2016 x64

**Comment by AnyoeDove** [comment]
😐既然移除了 MinGW 的版本 那这个 issue 暂时关闭惹...

**Comment by imgk** [comment]
I tried to rebuild MinGW version again from the newest version of original repo with different compiling config, and it crashed again and again. So I add MinGW version from https://github.com/Windendless/simple-obfs, and it works well. Just a little bit of out of date.

**Comment by AnyoeDove** [comment]
yeah MinGW version is better than cygwin and msys. btw i think this repo name should be simple-obfs-windows~
