### ISSUE TITLE
Wish continued maintenance

### ISSUE THREAD

**Issue by Platway** [imgk/simple-obfs-Cygwin#9]
Although MinGW version has been provided officially, the official version has a severe issue (https://github.com/shadowsocks/simple-obfs/issues/194), which does not occur with the version I downloaded here (v0.0.5 msys2-x86-64.zip). So I do hope  this repo will be updated continuously in the future. Thank you very much!

**Comment by imgk** [comment]
I wish I could provide maintenance for this repository, but sadly I've recently changed my platform from windows to Mac OS. Sorry for stopping maintenance.

**Comment by Platway** [comment]
Could you please share with me a detailed instruction on compiling and releasing it so that I can continue maintenance? Thanks a lot!

**Comment by imgk** [comment]
There is no difference between compiling with linux and with msys2. You can just try. If you have some issues when compiling, just ask me.
